import type * as monaco from 'monaco-editor';
export interface AllThemes {
    active4d: monaco.editor.IStandaloneThemeData;
    'all-hallows-eve': monaco.editor.IStandaloneThemeData;
    amy: monaco.editor.IStandaloneThemeData;
    'birds-of-paradise': monaco.editor.IStandaloneThemeData;
    blackboard: monaco.editor.IStandaloneThemeData;
    'brilliance-black': monaco.editor.IStandaloneThemeData;
    'brilliance-dull': monaco.editor.IStandaloneThemeData;
    'chrome-devtools': monaco.editor.IStandaloneThemeData;
    'clouds-midnight': monaco.editor.IStandaloneThemeData;
    clouds: monaco.editor.IStandaloneThemeData;
    cobalt: monaco.editor.IStandaloneThemeData;
    dawn: monaco.editor.IStandaloneThemeData;
    dreamweaver: monaco.editor.IStandaloneThemeData;
    eiffel: monaco.editor.IStandaloneThemeData;
    'espresso-libre': monaco.editor.IStandaloneThemeData;
    github: monaco.editor.IStandaloneThemeData;
    idle: monaco.editor.IStandaloneThemeData;
    katzenmilch: monaco.editor.IStandaloneThemeData;
    'kuroir-theme': monaco.editor.IStandaloneThemeData;
    lazy: monaco.editor.IStandaloneThemeData;
    'magicwb--amiga-': monaco.editor.IStandaloneThemeData;
    'merbivore-soft': monaco.editor.IStandaloneThemeData;
    merbivore: monaco.editor.IStandaloneThemeData;
    'monokai-bright': monaco.editor.IStandaloneThemeData;
    monokai: monaco.editor.IStandaloneThemeData;
    'night-owl': monaco.editor.IStandaloneThemeData;
    'oceanic-next': monaco.editor.IStandaloneThemeData;
    'pastels-on-dark': monaco.editor.IStandaloneThemeData;
    'slush-and-poppies': monaco.editor.IStandaloneThemeData;
    'solarized-dark': monaco.editor.IStandaloneThemeData;
    'solarized-light': monaco.editor.IStandaloneThemeData;
    spacecadet: monaco.editor.IStandaloneThemeData;
    sunburst: monaco.editor.IStandaloneThemeData;
    'textmate--mac-classic-': monaco.editor.IStandaloneThemeData;
    'tomorrow-night-blue': monaco.editor.IStandaloneThemeData;
    'tomorrow-night-bright': monaco.editor.IStandaloneThemeData;
    'tomorrow-night-eighties': monaco.editor.IStandaloneThemeData;
    'tomorrow-night': monaco.editor.IStandaloneThemeData;
    tomorrow: monaco.editor.IStandaloneThemeData;
    twilight: monaco.editor.IStandaloneThemeData;
    'upstream-sunburst': monaco.editor.IStandaloneThemeData;
    'vibrant-ink': monaco.editor.IStandaloneThemeData;
    'xcode-default': monaco.editor.IStandaloneThemeData;
    zenburnesque: monaco.editor.IStandaloneThemeData;
    iplastic: monaco.editor.IStandaloneThemeData;
    idlefingers: monaco.editor.IStandaloneThemeData;
    krtheme: monaco.editor.IStandaloneThemeData;
    monoindustrial: monaco.editor.IStandaloneThemeData;
}
export declare const allThemes: AllThemes;
export default allThemes;
